language: node_js
node_js:
- '0.12'
env:
  global:
  - secure: DpsmYf6J1LFZFdoRzOYfeIVJ9vXdGheO/csja2XctzIe7syBCOL0ehdHQaWQyaSjhlZpMbfPXRipCX19i1L01H4dxFEAWJt5wTqF9m1acW0tTnGY0BBPrcwYj/MFSyWRvGjNA29OSvSk81nurX0ha4KfYDcTgFCtR99nDo2DkMU=
  - secure: Zp9HzkVsKKrg3t40RqZUggjQs7aqnkryhEUpFIBa8NOuMpgOw+wfuz4lb0W+KuQGBDJOxeGymXljcNhhYdu5AllAA0ZpvtkcUm5s19mCjJARSUCwWjWT0p01t+pLSzpEf5yJW3EvgRCfq2YQKkJOBSVcHw39gNaQ/xvyQKteqwg=
  - secure: cI17hoQBXWtaaZwXPOW4sRES7d44Xt//CL6OBN8KLJU029CK3b5wTk86oZwS+WaZqQYZOcHa5uSDUzIXIZXlz56s9SvnBslM8l3mpaZHVsI46FN/b29QdEtPiWABipHXPn87RoRBKPPzdZEv20kp2KSLm69jXjSUrX18NJn4Ltw=
  - CI=true
after_script:
- "./node_modules/.bin/lcov-result-merger './coverage/**/lcov.info' | ./node_modules/coveralls/bin/coveralls.js"
- "./node_modules/.bin/lcov-result-merger './coverage/**/lcov.info' | ./node_modules/.bin/codeclimate"
